spring.application.name=Toolkit-Bridge

server.port=8080
logging.level.toolbridge=DEBUG


spring.datasource.url=jdbc:sqlite:./data/toolkit-bridge.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never


app.workspace.bots-root=workspace

toolkit.llm.openai-like.providers[0].name=lmstudio
toolkit.llm.openai-like.providers[0].base-url=http://192.168.1.116:11434/v1
toolkit.llm.openai-like.providers[0].api-key=sk-lm-LpbnlScU:Us605OryWCTJzgmSSzo4
toolkit.llm.openai-like.providers[0].default-model=qwen3.5-9b

toolkit.llm.openai-like.providers[1].name=ollama
toolkit.llm.openai-like.providers[1].base-url=http://localhost:11434/v1
toolkit.llm.openai-like.providers[1].api-key=
toolkit.llm.openai-like.providers[1].default-model=qwen3.5:9b

# toolkit.llm.openai-like.providers-properties[2].name=openai
# toolkit.llm.openai-like.providers-properties[2].base-url=https://api.openai.com/v1
# toolkit.llm.openai-like.providers-properties[2].api-key=${OPENAI_API_KEY}
# toolkit.llm.openai-like.providers-properties[2].default-model=gpt-4.1-mini