
@agentId = Cortex

### Create bot
POST http://localhost:8080/api/admin/agents
Content-Type: application/json
Accept: application/json

{
  "agentId": "{{agentId}}"
}

> {%
    client.test("Status is 201", function() {
        client.assert(response.status === 201, "Le status devrait être 201");
    });
%}
